name = "aiken-lang/lock-unlock"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/lock-unlock'"

[repository]
user = "jingles"
project = "test1"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.0-beta"
source = "github"

[config]
